const recipes = [
  {
    title: 'First recipe',
    image: '/cookbook.png',
    time: '1:20',
    source: 'Place',
    servings: 2,
    dairy: true,
    gluten: true,
    vegan: false,
    vegetarian: false,
    ingredients: [
      {
        name: 'Bread',
        amount: 2,
        measure: 'pcs',
      },
      {
        name: 'Cheese',
        amount: 100,
        measure: 'gr',
      },
      {
        name: 'Tomato',
        amount: 1,
        measure: 'pcs',
      },
      {
        name: 'Milk',
        amount: 150,
        measure: 'ml',
      },
    ],
    steps: ['Mix all Ingredients', 'Pour to a bowl', 'Eat everything'],
  },
  {
    title: 'Another recipe',
    image: '/cookbook.png',
    time: '0:50',
    source: 'Different place',
    dairy: true,
    gluten: false,
    vegan: false,
    vegetarian: true,
  },
  {
    title: 'Last recipe',
    image: '/cookbook.png',
    time: '2:40',
    source: 'Space',
    dairy: true,
    gluten: true,
    vegan: true,
    vegetarian: true,
  },
  {
    title: 'First recipe',
    image: '/cookbook.png',
    time: '1:20',
    source: 'Place',
    dairy: true,
    gluten: true,
    vegan: false,
    vegetarian: false,
  },
  {
    title: 'Another recipe',
    image: '/cookbook.png',
    time: '0:50',
    source: 'Different place',
    dairy: true,
    gluten: false,
    vegan: false,
    vegetarian: true,
  },
  {
    title: 'Last recipe',
    image: '/cookbook.png',
    time: '2:40',
    source: 'Space',
    dairy: true,
    gluten: true,
    vegan: true,
    vegetarian: true,
  },
];

export default recipes;
