/* eslint-disable @next/next/no-head-element */
'use client';
import './globals.css';
import Add from '../components/Add/Add';
import Footer from '../components/Footer/Footer';
import Header from '../components/Header/Header';
import Recipe from '../components/Recipe/Recipe';
import useUserStorage from '../state/useUserStorage';
import useRecipeStorage from '../state/useRecipeStorage';
import { useEffect } from 'react';

export default function RootLayout({ children }) {
  const { isLoggedIn, logIn } = useUserStorage((state) => ({
    isLoggedIn: state.isLoggedIn,
    logIn: state.logIn,
  }));
  const recipe = useRecipeStorage((state) => state.recipe);

  useEffect(() => {
    if (localStorage.getItem('jwt')) {
      logIn();
    }
  }, []);

  return (
    <html>
      <head>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/cookbook.ico' />
      </head>
      <body>
        <Header />
        {children}
        {isLoggedIn && <Add />}
        {Object.keys(recipe).length !== 0 && <Recipe {...recipe} />}
        <Footer />
      </body>
    </html>
  );
}
