/* eslint-disable @next/next/no-head-element */
import './globals.css';
import Header from './header';
import Search from '../components/Search/search';

export default function RootLayout({ children }) {
  return (
    <html>
      <head>
        <title>Cookbook</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/cookbook.ico' />
      </head>
      <body>
        <Header />
        <Search />
        {children}
      </body>
    </html>
  );
}
